### ISSUE TITLE
Ревизия каталога #1

### ISSUE THREAD

**Issue by bopoh13** [pMetro/pmetro.github.io#3]
### Вопрос
Судя по всему, _каталог_ собирается через скрипт `update.sh`. Что делать с файлами и ссылками, которые есть в репозитории и файле `maps.html`?
### Описание
_Каталог_ приложения находится в файле `Files.xml`, но в нём нет ссылок на
https://github.com/pMetro/pmetro.github.io/blob/f5083b015b9de089baea2c737cb071fc910ffb2e/maps.html#L149-L152
https://github.com/pMetro/pmetro.github.io/blob/f5083b015b9de089baea2c737cb071fc910ffb2e/maps.html#L153-L158

**Comment by Utyff** [comment]
update.sh сделал Dimqua, я вручную архивировал и обновлял каталог.

Файлы скачиваются с сайта  https://pmetro.github.io/
Его урл, по умолчанию, прописан в программе.



Gennady.
/////

**Comment by dimqua** [comment]
> Что делать с файлами и ссылками, которые есть в репозитории и файле maps.html?

Я пока тупо обновляю то, что Борис выкладывает у себя, плюс еще 4 карты от @MrSuperWolf появились.

> Каталог приложения находится в файле Files.xml, но в нём нет ссылок на ...

Это я специально так сделал, т.к. Moscow3d, MoscowTrams, MoscowTrolleys и MoscowZelBuses не работают в мобильной версии, последние 3 частично заменяет Moscow_Mobile. Перспективную схему заменил на Moscow_Next, а остальные убрал из _каталога_, как устаревшие, но можно вернуть.

**Comment by bopoh13** [comment]
@dimqua, просто хотел уточнить. Значит в репозитории есть карты, которые не работают в мобильной версии. Спасибо, буду знать.
